version: "3.3"
services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    volumes:
      - .:/usr/src/app
  sidekiq:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
    command: "bundle exec sidekiq -r ./config/sidekiq.rb"

