version: "3.3"
services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4567:4567"
    environment:
      REDIS_URL: "redis://redis:6379"
      DISBURSEMENTS_DATASET_SOURCE: './dataset/disbursements.json'
  sidekiq:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
      DISBURSEMENTS_DATASET_SOURCE: './dataset/disbursements.json'
    command: "bundle exec sidekiq -r ./config/sidekiq.rb"
  rspec:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      DISBURSEMENTS_DATASET_SOURCE: './spec/support/dataset/disbursements.json'
    command: "rspec spec/"
